name: Quality Assurance

on: [push]

jobs:
  quality-assurance:
    name: QA on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v1

      - uses: dart-lang/setup-dart@v1.3

      - run: dart pub get
      - run: dart test .
      - run: dart analyze .