name: Quality Assurance

on: [push]

jobs:
  quality-assurance:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Running analyze
        run: flutter analyze .
        with:
          flutter_package: true
      - name: Running tests
        run: flutter test .
        with:
          flutter_package: true